qa/urls.py
from django.conf.urls import url, include

from qa import views
from qa import speaker_urls, audience_urls

urlpatterns = [
    url(r'^lec/(?P<passcode>[\w\-]+)/', include(speaker_urls, namespace="lecturer")),
    url(r'^(?P<passcode>[\w\-]+)/', include(audience_urls, namespace="audience")),
]

qanda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from dashboard import urls as dash_urls
from core import urls as core_urls
from qanda import views
from qa import urls as qa_urls



urlpatterns = [

    url(r'^_admin/', admin.site.urls),


    # main Index landing page - "about"

    url(r'^$', views.Index.as_view(), name='index'),

    # All user authentication functions will begin with url "_account"

    url(r'^_accounts/login/', auth_views.LoginView.as_view(
        template_name = 'accounts/login.html',
        redirect_authenticated_user = True),
        name='login'),

    url(r'^_accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    url(r'^_accounts/signup/', views.Signup.as_view(), name='signup'),

    # Urls for the dashboard side of the application - Users who are actually buying the product.

    url(r'^_dashboard/', include(dash_urls, namespace= "dashboard")),

    # Urls for core. The rest_framework namespace needs to be a root namespace so it will have
    # to live here

    url(r'^_core/', include(core_urls, namespace= "core")),
    url(r'^_api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    # This will be the urls for the questioner side - another application
    url(r'^', include(qa_urls, namespace= "qa")),

]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _

# **** Each class represents a table in the Relation SQL-Queried backend database ***** #



''' custom user model for later extensibility '''

# Username will be validated as an email
username_validator = EmailValidator()

class User(AbstractUser):

    # same username as AbstractUser - but the validator is an email validator
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )



# Events are disjoint scenarios that the user will need to this application
class Event(models.Model):
    name = models.CharField(max_length = 1024)
    
    date_created = models.DateField(auto_now_add = True)
    
    description = models.TextField()
    
    location = models.CharField(max_length = 2048)
    
    owner = models.ForeignKey(User)
    
    event_type = models.CharField(max_length = 1024)
    
    start_date = models.DateField()
    
    end_date = models.DateField()
    
    is_open = models.BooleanField()
    
    time_zone = models.CharField(max_length = 1024) # to allow for users accross the globe
    
    passcode = models.CharField(max_length = 100, unique = True) # how audience will access the event
    
    def get_duration(self):
        return self.end_date - self.start_date
    
    def __str__(self):
        return self.name
    
       
    
# Each session is an instance of a QandA
class Session(models.Model):
    name = models.CharField(max_length = 1024)
    
    event = models.ForeignKey(Event)
    
    description = models.TextField(default = "")
    
    location = models.CharField(max_length = 2048)

    date_created = models.DateField(auto_now_add=True)
    
    allow_anonymous = models.BooleanField(default = False)
    
    allow_comments = models.BooleanField(default = False)
    
    

class Question(models.Model):
    content = models.TextField()
    
    session  = models.ForeignKey(Session, null = True)
    
    date_created = models.DateTimeField(auto_now_add = True)
    
    questioner = models.ForeignKey(User, null = True, blank = True) # allow for anonymous questions
    
    is_anonymous = models.BooleanField(default = True)
    
    upvotes = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    
    downvotes = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])

    sender_id = models.CharField(max_length=2046, default = "")

    answered = models.BooleanField(default=False)
    
    def net_votes(self):
        return self.upvotes - self.downvotes

    def save(self, **kwargs):
        # this needs to be abstracted away into an abstract models class
        if type(self).objects.filter(pk = self.pk).exists():
            self.original_object = type(self).objects.get(pk = self.pk)
        else:
            self.original_object = None
        super(Question, self).save(**kwargs)
    

class Comment(models.Model):
    content = models.TextField()
    
    question = models.ForeignKey(Question)
    
    date_created = models.DateTimeField(auto_now_add = True)
    
    commenter = models.ForeignKey(User, blank = True, null = True)
    
    upvotes = models.PositiveIntegerField()
    
    downvotes = models.PositiveIntegerField()
    
    def net_votes(self):
        return self.upvotes - self.downvotes
    


    
class Speaker(models.Model):
    name = models.CharField(max_length = 256)
    
    session = models.ForeignKey(Session)
    
    title = models.CharField(max_length = 512)
    
    company = models.CharField(max_length = 512)
    
    bio = models.TextField()
    
    

''' ********************************  SIGNALS  ******************************************   '''

# a seperate signals.py file requires us to import it early in the app's startup - pain.

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
import json
import ably

from .models import *
from core.api.serializers import QuestionSerializer

@receiver(post_save, sender=Event)
def create_event_main_session(sender, instance, created, **kwargs):
    if created:
        Session.objects.create(event=instance, name = instance.name)



"""

Channel names format: same as api urls but forward slashes replaced with dashes
NOTE: all detail operations are merged with LIST operations - there is only one channel
endpoint for all operations on an object. Listed below

Receiving creations/updates from Questions: "session-<session_pk>-questions"
...
...



"""

@receiver(post_save, sender=Question)
def send_new_question(sender, instance, created, **kwargs):
    orig = instance.original_object
    # Get channel based on API endpoint
    rest = ably.AblyRest('1Y5S8g.dbCwWg:rUcb_d26MjLV0giu')
    channel = rest.channels.get('session-%d-questions' % instance.session.pk)
    if created:
        channel.publish('create', json.dumps(QuestionSerializer(instance).data))
    else:
        if orig and \
                (orig.content != instance.content or
                 orig.upvotes != instance.upvotes or
                 orig.answered != instance.answered):
            channel.publish("update", json.dumps(QuestionSerializer(instance).data))

@receiver(post_delete, sender=Question)
def send_delete_question(sender, instance,**kwargs):
    rest = ably.AblyRest('1Y5S8g.dbCwWg:rUcb_d26MjLV0giu')
    channel = rest.channels.get('session-%d-questions' % instance.session.pk)
    channel.publish('delete', json.dumps(QuestionSerializer(instance).data))
    
    
    

qa/models.py
from django.db import models

# Create your models here.

qa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic

from core.models import Event, Session, Question

#main QA audience web app
class SessionList(generic.DetailView):
    model = Event
    slug_field = "passcode"
    slug_url_kwarg = "passcode"

class SessionDetail(generic.DetailView):
    model = Session

    def post(self, request, *args, **kwargs):
        passcode = kwargs.pop("passcode")
        pk = kwargs.pop("pk")
        content = request.POST['content']
        Question.objects.create(content = content, session = self.get_object())
        return redirect("qa:session-detail", passcode = passcode, pk = pk )

qa/templates/qa/audience/qa-main.html
{% extends 'dashboard/bs_template/base.html' %}
{% load static sekizai_tags %}

  {% block content %}

    {% addtoblock "css" %}

    {% endaddtoblock %}
    <div class="container" style="min-height: 800px;">
      <br /><br /><br />
        <h4 style="text-align: center;">Welcome to {{ object.name }}!</h4>
        <p style="text-align: center;">Select a room below</p>


        <div class="row justify-content-center">
          <div class="col-sm-8 mt-4">
            {% for session in object.session_set.all %}
              <div class="card">
                <div class="card-body">
                  <div class ="row">
                    <div class="col-md-9">
                      <h3 class="card-title">{{ session.name }} </h3>
                    </div>
                    <div class="col-md-3 text-md-right">
                      <a href="{% url 'qa:audience:session-detail' passcode=object.passcode pk=session.pk %}" class="btn btn-outline-secondary" role="button">Enter</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            <!-- /.card -->

          </div>
          <!-- /.col-lg-9 -->

        </div>




      <div id="react-root"></div>
      {% comment %} Add the javascript files using django's template blocks {% endcomment %}
      {% addtoblock 'js' %}

    {% endaddtoblock %}
   </div>
  {% endblock %}

qa/templates/qa/audience/session-detail.html
{% extends 'dashboard/bs_template/base.html' %}
{% load static sekizai_tags %}

  {% block content %}

    {% addtoblock "css" %}
      <link href="{%  static 'qa/audience/css/session-detail.css' %}" rel="stylesheet">
    {% endaddtoblock %}

    <div class="container-fluid">
      <br /><br /><br /><br />


      <div id="react-root"></div>

      {% comment %} Add the javascript files using django's template blocks {% endcomment %}
      {% addtoblock 'js' %}

        <script src="//cdn.ably.io/lib/ably.min-1.js"></script>
        <script type="text/javascript">
          var _realtime = new Ably.Realtime('1Y5S8g.5Tq2og:WNvhN6i34FJpKT-U');
          var s_p_k = {{ object.pk}};
        </script>
        <script type="text/babel" src="{% static 'qa/audience/sessionDetail.jsx' %}"></script>
      {% endaddtoblock %}
   </div>
  {% endblock %}